---
# cassandra role sets up a cassandra node.

 - name: Install JNA library
   apt: pkg=libjna-java update-cache=yes 

# Needed for add-apt-repository
 - name: Install python-software-properties
   apt: pkg=python-software-properties state=installed update-cache=yes
   tags:
     - apt

 - name: Add repository key
   apt_key: data="{{ lookup('file', '4BD736A82B5C1B00.gpg') }}"  state=present
   tags:
     - apt

 - name: Add Cassandra 2.0 repository
   apt_repository: repo='{{ cassandra_2_0.repo }}' state=present
   when: cassandra.version_branch == '2.0'
   tags:
     - apt

 - name: Install Cassandra
   apt: pkg=cassandra={{cassandra.version}} state=present update-cache=yes
   register: cassandra_install
   tags:
     - packages

 - name: Install Cassandra config file
   template: src=cassandra-{{cassandra.version_branch}}.yaml dest=/etc/cassandra/cassandra.yaml
   notify: restart cassandra
   tags:
     - configuration

 - name: Install log4j config file
   template: src=log4j-server.properties dest=/etc/cassandra/log4j-server.properties
   notify: restart cassandra
   tags:
     - configuration

