---
# This role contains plays that install and configure Java

# Setup Oracle Java 7
# https://www.digitalocean.com/community/articles/how-to-install-java-on-ubuntu-with-apt-get

 - name: Install supporting code based on Python
   apt: 
     name=python-software-properties
     state=installed

 - name: Add a repository that contains Oracle Java
   apt_repository: 
     repo='ppa:webupd8team/java'  

 - name: Update APT cache
   apt:  
     update_cache=yes

 - name: Install debian configuration utilities
   apt:
     name=debconf-utils
     state=installed

 - name: Copy the answers for the Oracle Java installation
   copy:
     src=apt-install-answers.txt
     dest=~/answers

 - name: Pre-answer the questions
   shell: 'cat ~/answers | debconf-set-selections'

 - name: Install Java
   apt:
    name=oracle-java7-installer

