---
# This role contains plays that install and configure NetKernel
# TODO: This works for Debian based systems only. Support non-Debian also
# Ref: http://www.cyberciti.biz/tips/howto-linux-shell-restricting-access.html

# TODO: Change the information shown in the license manager to reflect the person doing the installation
#

 - name: create user netkernel
   user:  
     name=netkernel 
     state=present 
     generate_ssh_key=yes 
     shell=/bin/bash uid=1100 
     createhome=yes

 - name: copy replace private key for user netkernel
   copy:
     src=netkernel_id_rsa
     dest=/home/netkernel/.ssh/id_rsa
     owner=netkernel
     group=netkernel
     mode=600

 - name: copy replacement public key for user netkernel
   copy:
     src=netkernel_id_rsa.pub
     dest=/home/netkernel/.ssh/id_rsa.pub
     owner=netkernel
     group=netkernel
     mode=644

 - name: copy .ssh/config for user netkernel
   copy:
     src=sshConfig
     dest=/home/netkernel/.ssh/config
     owner=netkernel
     group=netkernel
     mode=664

 - name: copy .ssh/known_hosts for user netkernel that has the reference for the license server
   copy:
     src=sshKnownHosts
     dest=/home/netkernel/.ssh/known_hosts
     owner=netkernel
     group=netkernel
     mode=644

 - name: Copy NetKernel 5 EE
   copy:
     src=1060-NetKernel-EE-5.2.1.jar
     dest=/home/{{ ansible_ssh_user }}/1060-NetKernel-EE-5.2.1.jar
     owner={{ ansible_ssh_user }}
     group={{ ansible_ssh_user }}
     mode=600

 - name: Install NetKernel
   shell: "java -Dunattended.install.directory=/opt/netkernel -jar /home/{{ ansible_ssh_user }}/1060-NetKernel-EE-5.2.1.jar"
# absent directory /opt/netkernel  when: java_version.stdout != '"1.7.0_45"'

 - name: Move NetKernel to /opt/netkernel-5.2.1
   shell: "mv /opt/netkernel /opt/netkernel-5.2.1"

 - name: Symlink back to /opt/netkernel
   shell: "ln -s /opt/netkernel-5.2.1 /opt/netkernel"

 - name: Copy license meter client to NetKernel
   copy:
     src=urn.com.ten60.netkernel.mod.license.mclient-1.3.0.sjar
     dest=/opt/netkernel/modules/urn.com.ten60.netkernel.mod.license.mclient-1.3.0.sjar

 - name: Copy license meter configuration
   copy:
     src=meterConfig.xml
     dest=/opt/netkernel/etc/meterConfig.xml

 - name: Add meter license client to modules.xml file
   lineinfile:
     state=present
     dest=/opt/netkernel/etc/modules.xml
     insertbefore='</modules>'
     line='<module runlevel="6">modules/urn.com.ten60.netkernel.mod.license.mclient-1.3.0.sjar</module>'

 - name: Add /etc/init.d/netkerneld file
   copy:
     src=netkerneld
     dest=/etc/init.d/netkerneld
     mode=755
    
 - name: Change permissions on /opt/netkernel
   shell: "chown -R netkernel:netkernel /opt/netkernel"

 - name: Change permissions on /opt/netkernel-5.2.1
   shell: "chown -R netkernel:netkernel /opt/netkernel-5.2.1"

 - name: Register /etc/init.d/netkerneld script with runtime manager
   shell: "update-rc.d netkerneld defaults"
   
# - name: Start NetKernel
#   shell: "service netkerneld start"

 - name: Start NetKernel
   service:
    name=netkerneld
    state=started




           