---
- hosts: experiment
  sudo: yes
  
  tasks:
  #
  # Configure groups and users
  #
  - name: create admin group
    action: group name=admin gid=1000 system=no 

  - name: create user admin
    action: user name=admin  group=admin shell=/bin/bash uid=1000
  - name: create user randy
    action: user name=randy  group=admin shell=/bin/bash uid=1001
  - name: create user teresa
    action: user name=teresa group=admin shell=/bin/bash uid=1002

  - name: setup authorized key for admin
    action: authorized_key user=admin  key='$FILE(~/.ssh/id_rsa.pub)'
  - name: setup authorized key for randy
    action: authorized_key user=randy  key='$FILE(~/.ssh/randy_rsa.pub)'
  - name: setup authorized key for teresa
    action: authorized_key user=teresa key='$FILE(~/.ssh/teresa_rsa.pub)'

