---
- hosts: setup-users
  user:  root
  
  tasks:
  #
  # Configure groups and users
  #
  - name: create admin group
    action: group name=admin gid=1000 system=no 

  - name: create user admin
    action: user name=admin  group=admin shell=/bin/bash uid=1000 password=$6$hFN6MFiP$7nk4PG5sw/n58bRLekTQmpo0IK4JO8ffP6BDyORroCRAy/ww7LmC5cwtAGpSSkiUfgBOwBxZ/14XdNWsSt7xg. 
  - name: create user randy
    action: user name=randy  group=admin shell=/bin/bash uid=1001 password=$6$hFN6MFiP$7nk4PG5sw/n58bRLekTQmpo0IK4JO8ffP6BDyORroCRAy/ww7LmC5cwtAGpSSkiUfgBOwBxZ/14XdNWsSt7xg.
  - name: create user teresa
    action: user name=teresa group=admin shell=/bin/bash uid=1002 password=$6$KNz3TNDR$TLRF1kwU.4Z4aCOjEo4DZ12dls0z.BVjhcpFfB8eS/xhkFq.1UD61lK6LJiC3wV9k92ovoXTLatX3zAT567rC/

  - name: setup authorized key for admin
    action: authorized_key user=admin  key='$FILE(~/.ssh/id_rsa.pub)'
  - name: setup authorized key for randy
    action: authorized_key user=randy  key='$FILE(~/.ssh/randy_rsa.pub)'
  - name: setup authorized key for teresa
    action: authorized_key user=teresa key='$FILE(~/.ssh/teresa_rsa.pub)'

